version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
