spring:
  application:
    name: order-service
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration/order
    default-schema: ${DB_SCHEMA}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000

security:
  jwt:
    secret: ${JWT_SIGNING_SECRET}

logging:
  structured:
    format:
      console: logstash
